FROM arm64v8/ubuntu:22.04 as rootfs-stage

ENV DIST ubuntu
ENV REV 22.04
ENV ARCH armv8

#NOTE: Install required packages
#RUN apt-get update && apt-get install -y --no-install-recommends \

#COPY root/ /
COPY init /
ENTRYPOINT ["/init"]
